### ISSUE TITLE
Could you add a PKGBUILD for building linux with llvm?

### ISSUE THREAD

**Issue by fokx** [h0tc0d3/kbuild#1]

**Comment by h0tc0d3** [comment]
@fokx If you are compiling the kernel just for yourself, then building via PKGBUILD only complicates the build. Therefore, I use a manual kernel build. https://www.archlinux.club/
kbuild helps me to automate the kernel build, I will update the script soon. It will also support out of tree builds and automatic building and merging of branches from git for kernel development. Also, I don't use heavy kernels, and I build a minimal kernel configuration and it only takes a couple of minutes to build the kernel.
